# Generated by Django 4.2.1 on 2024-06-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.FileField(null=True, upload_to='imagenes/'),
        ),
    ]
